import { Platform } from 'react-native';

import { apiClient, unwrap } from './apiClient';
import { env } from '../config/env';
import { formatFileSize } from '../utils/format';
import type { ApiSuccess } from '../types/api';
import type { ResearchSession } from '../types/lawyer';
import type {
  AiAnalyzeAccepted,
  AiSessionDetail,
  PickedFile,
} from '../types/ai';

/**
 * The AI Smart Case Assistant.
 *
 * ── How the endpoint actually behaves ─────────────────────────────────────
 *
 * `POST /ai/smart-case/analyze` is **asynchronous**. It answers `202` with a
 * `sessionId` and then runs the pipeline detached, via `setImmediate`. It does
 * not return a result, and waiting on the response for one would wait forever.
 * Progress is read back from `GET /ai/smart-case/session/:id`.
 *
 * Limits enforced server-side, all of them reported rather than guessed:
 *   - 1-10 documents, and **at least one is required** (422 without)
 *   - at most 1 voice file
 *   - 10 MB per file (400), allowlisted MIME types (415)
 *   - at most 3 analyses running per client (429)
 *   - the pipeline's own budget is 8 minutes
 *
 * ── Idempotency, and why the key goes in the body ─────────────────────────
 *
 * The controller accepts the key from `X-Request-Id` *or* a `requestId` form
 * field, and says why in its own comment: the reverse proxy in front of the
 * app answers CORS preflight itself with a fixed allowlist that omits
 * `X-Request-Id`, so a browser cannot send the header.
 *
 * This client sends the **form field only**, on every platform. The controller
 * checks the header first and falls back to the body, so one code path works
 * everywhere — and there is no custom header to trip a preflight, which is the
 * same trap that broke login on web.
 *
 * Without a key, a retried upload starts a second analysis instead of
 * rejoining the running one.
 */

/**
 * Appends a picked file to FormData in whatever form the platform needs.
 *
 * React Native's FormData accepts `{uri, name, type}` and reads the file from
 * disk itself. The browser's does not — it needs the actual Blob, or the part
 * is serialised as the string "[object Object]" and the upload silently
 * carries no file at all.
 */
const appendFile = (form: FormData, field: string, file: PickedFile): void => {
  if (Platform.OS === 'web' && file.file) {
    // The three-argument form (value plus filename) is the DOM's, and React
    // Native's FormData type declares only two — so the call is widened here
    // rather than losing the filename, which the backend uses to derive the
    // stored extension.
    (form.append as (
      name: string,
      value: Blob,
      fileName?: string,
    ) => void)(field, file.file as Blob, file.name);
    return;
  }

  form.append(field, {
    uri: file.uri,
    name: file.name,
    type: file.type || 'application/octet-stream',
  } as unknown as Blob);
};

export interface AnalyzeInput {
  /** 1-10. The backend rejects an empty list with 422. */
  documents: PickedFile[];
  /** Optional. One file, an allowlisted audio type. */
  voice?: PickedFile | null;
  /** The client's own written notes. Truncated server-side at 5000. */
  issueDescription?: string;
  /** A transcript produced on the device. Truncated server-side at 20000. */
  voiceTranscript?: string;
  /** "en" | "hi" | "te" — the backend's enum. Anything else is ignored. */
  voiceLanguage?: string;
  /** Idempotency key. Generated by the caller and reused across retries. */
  requestId: string;
  /** 0-1, for the upload progress bar. */
  onUploadProgress?: (fraction: number) => void;
}

export interface AiChatInput {
  message: string;
  conversationId?: string;
  mode?: 'chat' | 'research';
}

export interface AiChatMessage {
  role: 'user' | 'model' | 'assistant';
  text: string;
  timestamp?: string;
}

export interface AiChatResponse {
  response: string;
  conversationId?: string;
  title?: string;
  messages?: AiChatMessage[];
}

export const aiApi = {
  /**
   * POST /ai/chat
   *
   * Conversational AI Legal Assistant endpoint connected to Gemini.
   */
  async chat(input: AiChatInput): Promise<AiChatResponse> {
    const response = await apiClient.post<ApiSuccess<AiChatResponse>>(
      '/ai/chat',
      {
        message: input.message,
        conversationId: input.conversationId,
        mode: input.mode || 'chat',
      },
    );
    return unwrap(response);
  },

  /**
   * GET /ai/conversations?mode=research
   *
   * The advocate's saved research sessions.
   *
   * `mode` is load-bearing. The controller filters research conversations with
   * `{mode: "research"}` and everything else with `{mode: {$ne: "research"}}`,
   * so omitting it here would list the *client* chat history instead — and
   * deleting from that list would wipe the wrong thing. See `resolveMode` in
   * `controllers/ai/aiController.js`, which explains why the two are separated.
   */
  async getResearchSessions(): Promise<ResearchSession[]> {
    const response = await apiClient.get<
      ApiSuccess<{ conversations: ResearchSession[] }>
    >('/ai/conversations', { params: { mode: 'research' } });
    return unwrap(response)?.conversations ?? [];
  },

  /**
   * GET /ai/conversations/:id
   *
   * Scoped to `{_id: id, userId}` server-side, so one advocate cannot open
   * another's research by guessing an id.
   */
  async getConversation(id: string): Promise<{
    id: string;
    title: string;
    messages: AiChatMessage[];
  }> {
    const response = await apiClient.get<
      ApiSuccess<{ conversation: { _id: string; title: string; messages: AiChatMessage[] } }>
    >(`/ai/conversations/${encodeURIComponent(id)}`);
    const conversation = unwrap(response)?.conversation;
    return {
      id: conversation?._id ?? id,
      title: conversation?.title ?? '',
      messages: conversation?.messages ?? [],
    };
  },

  /** DELETE /ai/conversations/:id — soft-deletes the advocate's own session. */
  async deleteConversation(id: string): Promise<void> {
    await apiClient.delete(`/ai/conversations/${encodeURIComponent(id)}`);
  },

  /**
   * POST /ai/transcribe  (multipart/form-data, field `audio`)
   *
   * Synchronous, unlike `analyze`: it answers with the text itself. Used by
   * the Post Case description field's dictation button.
   *
   * `language` is optional and means "detect it" when absent, which is what
   * the recorder's Auto setting wants. The response carries the language the
   * server detected back, as a label — nothing here converts the transcript.
   *
   * Returns 500 when GEMINI_API_KEY is unset server-side; that message is
   * surfaced verbatim rather than being reported as a network failure.
   */
  async transcribe(
    audio: PickedFile,
    language?: string,
  ): Promise<{ transcript: string; language: string }> {
    const form = new FormData();
    appendFile(form, 'audio', audio);
    if (language) {
      form.append('language', language);
    }

    const response = await apiClient.post<
      ApiSuccess<{ transcript: string; language: string }>
    >('/ai/transcribe', form, {
      // Unset, not "multipart/form-data" — see `analyze` for why naming the
      // type without its boundary produces an unparseable body.
      headers: { 'Content-Type': undefined },
      timeout: 120000,
    });

    return unwrap(response);
  },

  /**
   * POST /ai/smart-case/analyze  (multipart/form-data)
   *
   * @returns the 202 acknowledgement — a session to poll, not a result.
   */
  async analyze(input: AnalyzeInput): Promise<AiAnalyzeAccepted> {
    // Every caller (AI Assistant, Post Case, Research) goes through here, so the
    // size ceiling is enforced once rather than trusted to each screen.
    const tooLarge = uploadTooLargeReason([...input.documents, input.voice]);
    if (tooLarge) {
      throw new Error(tooLarge);
    }

    const form = new FormData();

    for (const document of input.documents) {
      appendFile(form, 'documents', document);
    }

    if (input.voice) {
      appendFile(form, 'voice', input.voice);
    }

    if (input.issueDescription?.trim()) {
      form.append('issueDescription', input.issueDescription.trim());
    }
    if (input.voiceTranscript?.trim()) {
      form.append('voiceTranscript', input.voiceTranscript.trim());
    }
    if (input.voiceLanguage) {
      form.append('voiceLanguage', input.voiceLanguage);
    }

    form.append('requestId', input.requestId);

    const response = await apiClient.post<ApiSuccess<AiAnalyzeAccepted>>(
      '/ai/smart-case/analyze',
      form,
      {
        // Deliberately unset, not set to multipart/form-data. The boundary is
        // generated per request; naming the type without it produces a body
        // the server cannot parse.
        headers: { 'Content-Type': undefined },
        // Uploads are slow and the default 20s timeout would abort a large
        // batch mid-flight. The pipeline's own budget is 8 minutes; this
        // covers only the transfer.
        timeout: 180000,
        onUploadProgress: event => {
          if (input.onUploadProgress && event.total) {
            input.onUploadProgress(
              Math.min(1, event.loaded / event.total),
            );
          }
        },
      },
    );

    return unwrap(response);
  },

  /**
   * GET /ai/smart-case/session/:id
   *
   * Polled while `status === 'processing'`. The server reaps its own stale
   * sessions on read, so a run abandoned by a restart comes back `failed`
   * rather than processing forever.
   */
  async getSession(sessionId: string): Promise<AiSessionDetail> {
    const response = await apiClient.get<ApiSuccess<AiSessionDetail>>(
      `/ai/smart-case/session/${encodeURIComponent(sessionId)}`,
    );
    return unwrap(response);
  },

  /** GET /ai/smart-case/history?limit= — capped at 50 server-side. */
  async getHistory(limit = 20): Promise<unknown[]> {
    const response = await apiClient.get<ApiSuccess<unknown[]>>(
      '/ai/smart-case/history',
      { params: { limit: String(limit) } },
    );
    return unwrap(response) ?? [];
  },

  /**
   * POST /ai/smart-case/session/:id/link-case  body `{caseId}`
   *
   * Ties a finished analysis to the case it produced. Called by the Post Case
   * flow once a case exists — Phase 3.
   */
  async linkCase(sessionId: string, caseId: string): Promise<void> {
    await apiClient.post<ApiSuccess<unknown>>(
      `/ai/smart-case/session/${encodeURIComponent(sessionId)}/link-case`,
      { caseId },
    );
  },
};

/**
 * The upload rules, mirrored from `backend/src/middleware/upload.middleware.js`
 * so the UI can reject a file before spending a minute uploading it.
 *
 * The server remains the authority — these exist to save a round trip, and a
 * file that slips past them still gets a real 400 or 415.
 */
export const UPLOAD_LIMITS = {
  maxDocuments: 10,
  maxFileBytes: 10 * 1024 * 1024,
  /** `EXTENSION_BY_MIME` minus the audio types. */
  documentMimeTypes: [
    'application/pdf',
    'image/jpeg',
    'image/jpg',
    'image/png',
    'image/webp',
    'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    'text/plain',
    'text/markdown',
    'text/csv',
  ],
  /** Shown to the user, and used as the web file input's `accept`. */
  documentExtensions: ['.pdf', '.jpg', '.jpeg', '.png', '.webp', '.docx', '.txt', '.md', '.csv'],
  audioMimeTypes: [
    'audio/mpeg',
    'audio/mp3',
    'audio/wav',
    'audio/m4a',
    'audio/x-m4a',
    'audio/mp4',
    'audio/webm',
    'audio/ogg',
    'audio/aac',
    'audio/3gpp',
    'audio/amr',
  ],
} as const;

/** The server's ceiling for one whole AI upload, in bytes, or null for none. */
export const maxAiUploadBytes = (): number | null =>
  env.aiUploadMaxMb === null ? null : Math.floor(env.aiUploadMaxMb * 1024 * 1024);

/** A single file can be no bigger than the backend's limit or the upload's. */
export const maxAiFileBytes = (): number => {
  const total = maxAiUploadBytes();
  return total === null ? UPLOAD_LIMITS.maxFileBytes : Math.min(UPLOAD_LIMITS.maxFileBytes, total);
};

/** Sum of the sizes we know. A file whose size the platform did not report counts as 0. */
export const knownTotalBytes = (files: ReadonlyArray<PickedFile | null | undefined>): number =>
  files.reduce((sum, file) => sum + (file?.size ?? 0), 0);

/**
 * Why a whole upload cannot be sent, or null when it can.
 *
 * Checked before sending because the alternative is worse: nginx rejects an
 * oversized body with an HTML 413 that has no CORS header, which a browser
 * reports as a CORS failure and the app could only guess at.
 */
export const uploadTooLargeReason = (
  files: ReadonlyArray<PickedFile | null | undefined>,
): string | null => {
  const max = maxAiUploadBytes();
  const total = knownTotalBytes(files);
  if (max === null || total <= max) {
    return null;
  }
  return `Your files add up to ${formatFileSize(total)}, but one upload can be at most ${formatFileSize(
    max,
  )}. Please remove a file or reduce the file sizes (for example, compress the PDF or scan at a lower resolution), then try again.`;
};

/**
 * Why a file cannot be sent, or null when it can.
 *
 * `.doc` is called out by name: the backend excludes it deliberately — it is a
 * pre-2007 binary format Gemini cannot read — and a generic "unsupported type"
 * would leave the user guessing what to convert.
 */
export const rejectionReasonFor = (file: PickedFile): string | null => {
  const maxBytes = maxAiFileBytes();
  if (file.size !== null && file.size > maxBytes) {
    return `${file.name} is ${formatFileSize(file.size)}, over the ${formatFileSize(
      maxBytes,
    )} limit. Please reduce or compress it and try again.`;
  }

  const name = file.name.toLowerCase();

  if (name.endsWith('.doc')) {
    return `${file.name} is an older .doc file, which cannot be read. Please save it as PDF or .docx.`;
  }

  const extensionAllowed = UPLOAD_LIMITS.documentExtensions.some(extension =>
    name.endsWith(extension),
  );
  const mimeAllowed =
    file.type !== null &&
    (UPLOAD_LIMITS.documentMimeTypes as readonly string[]).includes(file.type);

  // The server accepts a file if *either* its MIME type or its extension is
  // allowlisted, so this mirrors that rather than being stricter.
  if (!extensionAllowed && !mimeAllowed) {
    return `${file.name} is not a supported file type.`;
  }

  return null;
};
