const AUTH_CODES = {
  EMAIL_ALREADY_REGISTERED: "EMAIL_ALREADY_REGISTERED",

  MOBILE_ALREADY_REGISTERED: "MOBILE_ALREADY_REGISTERED",

  NAME_ALREADY_IN_USE: "NAME_ALREADY_IN_USE",

  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",

  ACTIVE_SESSION_EXISTS: "ACTIVE_SESSION_EXISTS",

  SESSION_EXPIRED: "SESSION_EXPIRED",

  ACCOUNT_INACTIVE: "ACCOUNT_INACTIVE",
};

module.exports = AUTH_CODES;
